@extends(backpack_view('blank'))
@section('content')
<div class="d-flex justify-content-between mb-3"><div><h2 class="mb-0">Candidatos SECOP</h2><small>{{ $prevalidacion->nombre_contratista }} · {{ $prevalidacion->cedula_o_nit }}</small></div><a class="btn btn-outline-secondary" href="{{ route('prevalidacion.show',$prevalidacion) }}">Volver</a></div>
@if($error)<div class="alert alert-danger">No se pudo consultar SECOP: {{ $error }}</div>@endif
<div class="alert alert-info">La sugerencia usa NIT de entidad, referencia, vigencia y valor. Confirma siempre el registro correcto. Un contrato vinculado a otro seguimiento no puede seleccionarse.</div>
<div class="card"><div class="table-responsive"><table class="table table-striped align-middle mb-0"><thead><tr><th>Sugerencia</th><th>Fuente</th><th>Entidad / identificador</th><th>Estado / fase</th><th>Fechas</th><th>Valor</th><th></th></tr></thead><tbody>
@forelse($candidates as $candidate)
<tr class="{{ !$candidate['disponible']?'table-secondary':'' }}"><td><span class="badge bg-{{ $candidate['puntaje']>=70?'success':($candidate['puntaje']>=40?'warning':'secondary') }}">{{ $candidate['puntaje'] }}%</span></td><td>{{ $candidate['fuente'] }}<br><small>{{ $candidate['tipo_registro'] }}</small></td><td>{{ $candidate['nombre_entidad'] ?? '-' }}<br><small class="text-break">{{ $candidate['referencia_contrato'] ?? $candidate['referencia_proceso'] ?? $candidate['identificador_externo'] }}</small></td><td>{{ $candidate['estado'] ?? '-' }}<br><small>{{ $candidate['fase'] ?? '' }}</small></td><td>{{ $candidate['fecha_inicio'] ?? $candidate['fecha_publicacion'] ?? '-' }} → {{ $candidate['fecha_fin'] ?? '-' }}</td><td>{{ is_numeric($candidate['valor_total_con_adiciones'] ?? null)?'$ '.number_format($candidate['valor_total_con_adiciones'],0,',','.'):'-' }}</td><td>@if($candidate['disponible'])<form method="POST" action="{{ route('prevalidacion.link',$prevalidacion) }}">@csrf<input type="hidden" name="fuente" value="{{ $candidate['fuente_codigo'] }}"><input type="hidden" name="identificador" value="{{ $candidate['identificador_externo'] }}"><button class="btn btn-sm btn-primary" onclick="return confirm('¿Confirmas este vínculo?')">Vincular</button></form>@else<span class="badge bg-dark">Ya utilizado</span>@endif @if($candidate['url']??false)<a href="{{ $candidate['url'] }}" target="_blank" class="btn btn-sm btn-link">SECOP</a>@endif</td></tr>
@empty<tr><td colspan="7" class="text-center text-muted py-4">No se encontraron contratos ni procesos para esta cédula y entidad.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
