@extends(backpack_view('blank'))
@section('content')
@foreach(['success','warning','error'] as $type) @if(session($type))<div class="alert alert-{{ $type==='error'?'danger':$type }}">{{ session($type) }}</div>@endif @endforeach
@if($refreshError)<div class="alert alert-warning">No se pudo refrescar SECOP: {{ $refreshError }}. Se conserva la última información.</div>@endif
<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><div><h2 class="mb-0">{{ $prevalidacion->nombre_reportado ?: $prevalidacion->nombre_contratista ?: 'Intención sin nombre' }}</h2><span class="text-muted">{{ $prevalidacion->clave_externa }} · {{ $prevalidacion->fuente->nombre }} · fila {{ $prevalidacion->fila_origen }}</span></div><div><a class="btn btn-outline-secondary" href="{{ route('prevalidacion.index') }}">Bandeja</a> <a class="btn btn-primary" href="{{ route('prevalidacion.edit',$prevalidacion) }}">Editar / normalizar</a></div></div>
@if($prevalidacion->nombre_requiere_revision)<div class="alert alert-warning"><strong>El nombre reportado requiere revisión.</strong> Puede contener cambios, reemplazos, cargos o comentarios. La cédula corresponde a la persona que ingresa; valida el nombre normalizado antes de enviar a Seguimiento.</div>@endif
@if($prevalidacion->numero_contrato_planeado && (!$prevalidacion->fecha_inicio_planeada || !$prevalidacion->fecha_fin_planeada))<div class="alert alert-danger"><strong>Fechas incompletas o inválidas en el Drive.</strong> Inicio reportado: {{ $prevalidacion->datos_origen['mapeados']['fecha_inicio'] ?? '-' }}. Finalización reportada: {{ $prevalidacion->datos_origen['mapeados']['fecha_fin'] ?? '-' }}. Integra conserva el texto original sin convertirlo en una fecha válida.</div>@endif
@if($prevalidacion->conflictos)<div class="alert alert-danger"><strong>Conflictos con Drive:</strong> Integra conservó los valores locales.<div class="table-responsive mt-2"><table class="table table-sm mb-0"><thead><tr><th>Campo</th><th>Integra</th><th>Drive</th><th></th></tr></thead><tbody>@foreach($prevalidacion->conflictos as $field=>$conflict)<tr><td>{{ $field }}</td><td>{{ is_array($conflict['integra']??null)?json_encode($conflict['integra']):($conflict['integra']??'-') }}</td><td>{{ is_array($conflict['drive']??null)?json_encode($conflict['drive']):($conflict['drive']??'-') }}</td><td><form method="POST" action="{{ route('prevalidacion.accept-drive',$prevalidacion) }}">@csrf<input type="hidden" name="field" value="{{ $field }}"><button class="btn btn-sm btn-outline-danger">Aceptar Drive</button></form></td></tr>@endforeach</tbody></table></div></div>@endif
@php
$money=fn($value)=>$value!==null?'$ '.number_format($value,0,',','.'):'-';
$date=fn($value)=>$value?->format('d/m/Y')?:'-';
$snap=$prevalidacion->vinculoSecop?->ultimaInstantanea;
@endphp
<div class="row">
<div class="col-lg-6">
<div class="card mb-3"><div class="card-header"><strong>Persona y origen</strong></div><div class="card-body"><div class="row g-3"><div class="col-12"><small class="text-muted">Nombre reportado en Drive</small><div>{{ $prevalidacion->nombre_reportado ?: '-' }}</div></div><div class="col-12"><small class="text-muted">Nombre normalizado para Integra</small><div>{{ $prevalidacion->nombre_contratista ?: 'Pendiente de revisión' }}</div></div><div class="col-6"><small class="text-muted">Documento de quien ingresa</small><div>{{ $prevalidacion->cedula_o_nit ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Celular</small><div>{{ $prevalidacion->celular ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Dependencia</small><div>{{ $prevalidacion->dependencia_origen ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Gerencia</small><div>{{ $prevalidacion->gerencia?->nombre ?: ($prevalidacion->datos_origen['mapeados']['gerencia'] ?? '-') }}</div></div><div class="col-4"><small class="text-muted">Número en cuadro</small><div>{{ $prevalidacion->numero_origen ?: '-' }}</div></div><div class="col-4"><small class="text-muted">Año</small><div>{{ $prevalidacion->anio ?: '-' }}</div></div><div class="col-4"><small class="text-muted">Fuente recursos</small><div>{{ $prevalidacion->fuente_recursos ?: '-' }}</div></div></div></div></div>
<div class="card mb-3"><div class="card-header"><strong>Formación reportada</strong></div><div class="card-body"><div class="row g-3"><div class="col-6"><small class="text-muted">Nivel académico</small><div>{{ $prevalidacion->nivel_academico ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Profesión / perfil</small><div>{{ $prevalidacion->profesion ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Especialización</small><div>{{ $prevalidacion->especializacion ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Maestría</small><div>{{ $prevalidacion->maestria ?: '-' }}</div></div></div></div></div>
</div>
<div class="col-lg-6">
<div class="card mb-3"><div class="card-header"><strong>Estado e intención contractual</strong></div><div class="card-body"><div class="row g-3"><div class="col-6"><small class="text-muted">Estado del Drive</small><div><span class="badge bg-primary">{{ $prevalidacion->estado_origen ?: '-' }}</span></div></div><div class="col-6"><small class="text-muted">Etapa en Integra</small><div>{{ str_replace('_',' ',$prevalidacion->etapa) }}</div></div><div class="col-6"><small class="text-muted">Número de contrato</small><div>{{ $prevalidacion->numero_contrato_planeado ?: 'Todavía no existe' }}</div></div><div class="col-6"><small class="text-muted">Duración</small><div>{{ $prevalidacion->tiempo_planeado_dias ?? '-' }} días</div></div><div class="col-4"><small class="text-muted">Inicio</small><div>{{ $date($prevalidacion->fecha_inicio_planeada) }}</div></div><div class="col-4"><small class="text-muted">Finalización</small><div>{{ $date($prevalidacion->fecha_fin_planeada) }}</div></div><div class="col-4"><small class="text-muted">Tiempo total</small><div>{{ $prevalidacion->tiempo_total_dias ?? '-' }} días</div></div><div class="col-6"><small class="text-muted">Valor mensual</small><div>{{ $money($prevalidacion->valor_mensual_planeado) }}</div></div><div class="col-6"><small class="text-muted">Valor inicial</small><div>{{ $money($prevalidacion->valor_total_planeado) }}</div></div></div></div></div>
<div class="card mb-3"><div class="card-header"><strong>Adición y resultado</strong></div><div class="card-body"><div class="row g-3"><div class="col-4"><small class="text-muted">Adición</small><div>{{ $prevalidacion->adicion ?: '-' }}</div></div><div class="col-4"><small class="text-muted">Inicio adición</small><div>{{ $date($prevalidacion->fecha_inicio_adicion) }}</div></div><div class="col-4"><small class="text-muted">Fin adición</small><div>{{ $date($prevalidacion->fecha_fin_adicion) }}</div></div><div class="col-4"><small class="text-muted">Días adición</small><div>{{ $prevalidacion->tiempo_adicion_dias ?? '-' }}</div></div><div class="col-4"><small class="text-muted">Valor adición</small><div>{{ $money($prevalidacion->valor_adicion) }}</div></div><div class="col-4"><small class="text-muted">Valor total contrato</small><div>{{ $money($prevalidacion->valor_total_contrato) }}</div></div><div class="col-6"><small class="text-muted">Evaluación</small><div>{{ $prevalidacion->evaluacion ?: '-' }}</div></div><div class="col-6"><small class="text-muted">Continúa</small><div>{{ $prevalidacion->continua ?: '-' }}</div></div><div class="col-12"><small class="text-muted">Observación</small><div>{{ $prevalidacion->observaciones ?: '-' }}</div></div><div class="col-12"><small class="text-muted">Sector</small><div>{{ $prevalidacion->sector ?: '-' }}</div></div>@if($prevalidacion->enlace_origen)<div class="col-12"><a href="{{ $prevalidacion->enlace_origen }}" target="_blank" rel="noopener">Abrir enlace reportado</a></div>@endif</div></div></div>
</div></div>
<div class="card mb-3"><div class="card-header d-flex justify-content-between"><strong>SECOP observado</strong><div>@if($prevalidacion->vinculoSecop)<form class="d-inline" method="POST" action="{{ route('prevalidacion.refresh',$prevalidacion) }}">@csrf<button class="btn btn-sm btn-outline-primary">Refrescar</button></form> <form class="d-inline" method="POST" action="{{ route('prevalidacion.unlink',$prevalidacion) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('¿Desvincular SECOP?')">Desvincular</button></form>@else<a class="btn btn-sm btn-primary" href="{{ route('prevalidacion.candidates',$prevalidacion) }}">Buscar y vincular</a>@endif</div></div><div class="card-body">@if($snap)<div class="row g-3"><div class="col-md-3"><small class="text-muted">Estado / fase</small><div>{{ $snap->estado ?: $snap->fase ?: '-' }}</div></div><div class="col-md-3"><small class="text-muted">Inicio</small><div>{{ $date($snap->fecha_inicio) }}</div></div><div class="col-md-3"><small class="text-muted">Fin</small><div>{{ $date($snap->fecha_fin) }}</div></div><div class="col-md-3"><small class="text-muted">Valor total</small><div>{{ $money($snap->valor_total) }}</div></div>@if($snap->url)<div class="col-12"><a target="_blank" href="{{ $snap->url }}">Abrir proceso SECOP</a></div>@endif</div>@else<p class="text-muted mb-0">Todavía no hay un proceso o contrato SECOP vinculado.</p>@endif</div></div>
<div class="card"><div class="card-header d-flex justify-content-between"><strong>Resultado en Integra</strong>@if($prevalidacion->seguimiento)<a href="{{ backpack_url('seguimiento/'.$prevalidacion->seguimiento_id.'/show') }}" class="btn btn-sm btn-success">Abrir Seguimiento #{{ $prevalidacion->seguimiento_id }}</a>@elseif($prevalidacion->etapa==='APROBADO_POR_ENVIAR' && $prevalidacion->nombre_contratista)<form method="POST" action="{{ route('prevalidacion.promote') }}">@csrf<input type="hidden" name="ids[]" value="{{ $prevalidacion->id }}"><button class="btn btn-sm btn-success">Enviar a Seguimiento</button></form>@endif</div><div class="card-body"><small class="text-muted">Última sincronización: {{ $prevalidacion->ultima_sincronizacion_at?->format('d/m/Y H:i') ?: 'No sincronizado' }}</small></div></div>
@endsection
