@extends(backpack_view('blank'))
@section('content')
<div class="d-flex justify-content-between mb-3"><div><h2 class="mb-0">Vincular Seguimiento con SECOP</h2><small>{{ $seguimiento->persona?->nombre_contratista }} · {{ $seguimiento->persona?->cedula_o_nit }}</small></div><a class="btn btn-outline-secondary" href="{{ backpack_url('seguimiento/'.$seguimiento->id.'/show') }}">Volver</a></div>
@if($error)<div class="alert alert-danger">{{ $error }}</div>@endif
<div class="alert alert-info">Los datos existentes se conservan como planeación. La selección SECOP se guardará aparte y puede deshacerse.</div>
<div class="card"><div class="table-responsive"><table class="table table-striped align-middle mb-0"><thead><tr><th>Sugerencia</th><th>Fuente</th><th>Entidad / referencia</th><th>Estado</th><th>Fechas</th><th>Valor</th><th></th></tr></thead><tbody>
@forelse($candidates as $candidate)<tr class="{{ !$candidate['disponible']?'table-secondary':'' }}"><td><span class="badge bg-{{ $candidate['puntaje']>=70?'success':($candidate['puntaje']>=40?'warning':'secondary') }}">{{ $candidate['puntaje'] }}%</span></td><td>{{ $candidate['fuente'] }}<br><small>{{ $candidate['tipo_registro'] }}</small></td><td>{{ $candidate['nombre_entidad']??'-' }}<br><small>{{ $candidate['referencia_contrato']??$candidate['referencia_proceso']??$candidate['identificador_externo'] }}</small></td><td>{{ $candidate['estado']??'-' }}<br><small>{{ $candidate['fase']??'' }}</small></td><td>{{ $candidate['fecha_inicio']??$candidate['fecha_publicacion']??'-' }} → {{ $candidate['fecha_fin']??'-' }}</td><td>{{ is_numeric($candidate['valor_total_con_adiciones']??null)?'$ '.number_format($candidate['valor_total_con_adiciones'],0,',','.'):'-' }}</td><td>@if(($candidate['tipo_registro']??'contrato')==='proceso')<span class="badge bg-info">Señal preliminar</span>@elseif($candidate['disponible'])<form method="POST" action="{{ route('seguimiento.secop.link',$seguimiento) }}">@csrf<input type="hidden" name="fuente" value="{{ $candidate['fuente_codigo'] }}"><input type="hidden" name="identificador" value="{{ $candidate['identificador_externo'] }}"><button class="btn btn-sm btn-primary" onclick="return confirm('¿Confirmar este contrato?')">Vincular</button></form>@else<span class="badge bg-dark">Ya utilizado</span>@endif @if($candidate['url']??false)<a class="btn btn-sm btn-link" target="_blank" href="{{ $candidate['url'] }}">SECOP</a>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No se encontraron candidatos.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
