@extends(backpack_view('blank'))
@section('content')
<div class="d-flex justify-content-between mb-3"><h2>{{ $fuente->exists?'Editar':'Nueva' }} fuente</h2><a class="btn btn-outline-secondary" href="{{ route('prevalidacion.sources.index') }}">Volver</a></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $fuente->exists?route('prevalidacion.sources.update',$fuente):route('prevalidacion.sources.store') }}">@csrf @if($fuente->exists)@method('PUT')@endif
@php $map=$fuente->mapeo_columnas?:[]; @endphp
<div class="card mb-3"><div class="card-header"><strong>Origen</strong></div><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Nombre</label><input class="form-control" name="nombre" value="{{ old('nombre',$fuente->nombre) }}" required></div><div class="col-md-5"><label class="form-label">Secretaría / entidad</label><select class="form-select" name="secretaria_id" required><option value="">Seleccione</option>@foreach($secretarias as $s)<option value="{{ $s->id }}" @selected((string)old('secretaria_id',$fuente->secretaria_id)===(string)$s->id)>{{ $s->nombre }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">NIT entidad</label><input class="form-control" name="nit_entidad" value="{{ old('nit_entidad',$fuente->nit_entidad) }}" required></div><div class="col-md-7"><label class="form-label">URL o ID del Google Sheet</label><input class="form-control" name="spreadsheet_url_o_id" value="{{ old('spreadsheet_url_o_id',$fuente->spreadsheet_url?:$fuente->spreadsheet_id) }}" required></div><div class="col-md-3"><label class="form-label">Pestaña</label><input class="form-control" name="hoja" value="{{ old('hoja',$fuente->hoja) }}" required></div><div class="col-md-2"><label class="form-label">Fila encabezados</label><input type="number" min="1" class="form-control" name="fila_encabezados" value="{{ old('fila_encabezados',$fuente->fila_encabezados?:1) }}" required></div><div class="col-md-3"><label class="form-label">Año que se sincroniza</label><input type="number" class="form-control" name="anio_objetivo" value="{{ old('anio_objetivo',$fuente->anio_objetivo?:2026) }}" required></div><div class="col-md-3"><label class="form-label">Columna ID estable</label><input class="form-control" name="columna_clave" value="{{ old('columna_clave',$fuente->columna_clave?:'ID_INTEGRA') }}" required></div><div class="col-md-3"><label class="form-label">Columna marca Integra</label><input class="form-control" name="columna_editado" value="{{ old('columna_editado',$fuente->columna_editado?:'EDITADO_EN_INTEGRA') }}"></div><div class="col-md-3 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="activa" value="0"><input class="form-check-input" type="checkbox" name="activa" value="1" @checked(old('activa',$fuente->exists?$fuente->activa:true))><label class="form-check-label">Fuente activa</label></div></div></div></div></div>
<div class="card"><div class="card-header"><strong>Equivalencias de columnas</strong></div><div class="card-body"><p class="text-muted">Escribe exactamente el encabezado que aparece en el cuadro. Cédula, nombre, estado y año son obligatorios. Los demás campos permiten reproducir en Integra la información del Drive.</p><div class="row g-3">
@foreach(\App\Http\Controllers\Admin\PrevalidacionFuenteController::MAPPING_FIELDS as $canonical=>$input)
<div class="col-md-4"><label class="form-label">{{ str_replace('_',' ',ucfirst($canonical)) }} @if(in_array($canonical,['cedula_o_nit','nombre_contratista','estado','anio']))<span class="text-danger">*</span>@endif</label><input class="form-control" name="{{ $input }}" value="{{ old($input,$map[$canonical]??'') }}" @required(in_array($canonical,['cedula_o_nit','nombre_contratista','estado','anio']))></div>
@endforeach
</div></div><div class="card-footer"><button class="btn btn-primary">Guardar fuente</button></div></div></form>
@endsection
